version: 2.1
jobs:
  Hello-World:
    docker:
      - image: circleci/node:10-browsers #alpine:3.7
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: List code contents 
          command: |
            echo 'This is where the code is read'
            ls -la
      - run:
          name: Container feature
          command: |
            node -v
  Run-After-Hello:
    docker:
      - image: circleci/node:10-browsers #alpine:3.7
    steps:
      - run:
          name: The Second Job
          command: |
            echo 'Hello World againnn!'
workflows:
 version: 2
 TestWorkflow:
    jobs:
      - Hello-World
      - Run-After-Hello:
          requires:
            - Hello-World