version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers #alpine:3.7
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
      - run:
          name: List code contents 
          command: |
            echo 'This is where the code is read'
            ls -la
      - run:
          name: Container feature
          command: |
            node -v